[package]
name = "prueba"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fluent-resmgr = "0.0.6"
unic-langid = "0.9.1"
fluent = "0.16.0"
fluent-langneg = "0.13.0"